config/routes.rb
Rails.application.routes.draw do
  root 'passages#show_all'

  get 'login', to: 'cookies#new'
  get 'logout', to: 'cookies#show_log_out'
  resource :cookies, { only: %i[create destroy] }

  resources :users, path_names: { new: 'signup' } do
    resource :bookmarks, { only: %i[show] }

    resources :passages, { only: %i[create destroy show] } do
      get 'bookmarks', to: 'bookmarks#show_passage_bookmarks'
      post 'bookmarks/check', to: 'bookmarks#try_create_bookmark'
    end

    resources :comments, { only: %i[create destroy show] } do
      get 'likes', to: 'likes#show_comment_likes'
      post 'likes/check', to: 'likes#try_create_like'
    end
  end

  patch 'users/:id/update-name-self-introduction', to: 'users#update_name_self_introduction'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments, dependent: :delete_all
  has_many :comment_likes, dependent: :delete_all
  has_many :passages, dependent: :delete_all
  has_many :passage_bookmarks, dependent: :delete_all

  attr_accessor :remember_token

  before_save { email.downcase! }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  VALID_ID_REGEX = /[a-zA-Z0-9_-]+/
  validates :id, presence: true, length: { maximum: 255 }, format: { with: VALID_ID_REGEX }, uniqueness: true,
                 user_id_unprohibited: true

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  validates :name, presence: true, length: { maximum: 255 }

  def self.digest(string)
    cost = if ActiveModel::SecurePassword.min_cost
             BCrypt::Engine::MIN_COST
           else
             BCrypt::Engine.cost
           end
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?

    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ApplicationHelper

  def new
    @user = User.new
  end

  def show
    @user = User.find_by(id: params[:id])

    @passages = User.joins(:passages).where(users: { id: params[:id] }).select('users.name as user_name, passages.*')
                    .order('passages.created_at desc').order('passages.user_id asc')

    @passages_bookmarks = Passage.eager_load(:passage_bookmarks).where(passages: { user_id: params[:id] })
                                 .select('passages.id as passage_id').order('passages.created_at desc').order('passages.user_id asc')
                                 .group('passages.id').count('passage_bookmarks.id').map { |_key, value| value }

                                 @has_user_logged_in = logged_in?
    @current_user = current_user
  end

  def create
    user = User.new(user_params)
    if user.save
      user.remember
      log_in(user)
      redirect_to root_url
    else
      render 'new'
    end
  end

  def update_name_self_introduction
    @user = User.find_by(id: params[:id])
    if @user.update(user_name_self_introduction_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def destroy
    @user.destroy
  end

  private

  def user_params
    params.require(:user).permit(:id, :name, :email, :password, :password_confirmation)
  end

  def user_name_self_introduction_params
    params.require(:user).permit(:name, :self_introduction)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div>
  <!--Todo: 直下href先変更する。画像の保存先によってupdate先のurlが変わる。画像の保存先を決めた後に取り組む-->
  <a href="{{ url_for('show_edit_user_image', user_id=current_user_id)}}">
    <button type="submit">
      <img src="data:image/png;base64, {{ user_image }}" width="150px" height="150px">
    </button>
  </a>
</div>
<div class="flex items-center justify-center">
  <div class="flex items-center justify-center rounded-md h-96 w-72">
    <div class="mx-1/5">
      <div class="flex items-center justify-center">
        <div class="w-5/5">
          <%= form_with(model: @user, url: {controller: 'users', action: 'update_name_self_introduction'}, local: true) do |f| %>
          <%= f.label :name, 'ユーザー名' %>
          <%= f.text_field :name, class: 'bg-white rounded-md h-7 mb-1.5 pl-2.5 w-full border-solid border-2 border-yellow-600', placeholder: 'ユーザー名' %>

          <%= f.label :self_introduction, '自己紹介' %>
          <%= f.text_area :self_introduction, class: 'bg-white rounded-md h-16 mb-1.5 pl-2.5 w-full border-solid border-2 border-yellow-600', placeholder: '自己紹介' %>

          <div class="flex items-center justify-center mt-1.5">
            <div class="rounded-md bg-yellow-600 h-7 w-4/5 hover:bg-yellow-500">
              <%= f.submit "更新する", class: 'text-center h-7 w-full' %>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="fixed" style="z-index: -1;">
  <!--Todo: 直下srcを変更する。画像の保存先を決めた後-->
  <img class="w-full" src="../static/img/login_background.png">
</div>
<div class="flex items-center justify-center h-screen">
  <div class="flex items-center justify-center rounded-md h-96 w-72 bg-yellow-200">
    <div class="my-auto mx-1/5">
      <div class="mb-7 text-center">
        <h1 class="text-4xl font-bold">ブクエモ！</h1>
        <p class="text-base">心揺さぶる文章がここにある</p>
      </div>

      <div class="flex items-center justify-center">
        <div class="w-4/5">
          <%= form_with(model: @user, local: true) do |f| %>
          <%= f.text_field :id, class: 'bg-white rounded-md h-7 mb-1.5 pl-2.5 w-full', placeholder: 'id' %>

          <%= f.text_field :name, class: 'bg-white rounded-md h-7 mb-1.5 pl-2.5 w-full', placeholder: 'ユーザー名' %>

          <%= f.email_field :email, class: 'bg-white rounded-md h-7 mb-1.5 pl-2.5 w-full', placeholder: 'Eメール' %>

          <%= f.password_field :password, class: 'bg-white rounded-md h-7 mb-1.5 pl-2.5 w-full', placeholder: 'パスワード' %>

          <%= f.password_field :password_confirmation, class: 'bg-white rounded-md h-7 mb-1.5 pl-2.5 w-full', placeholder: 'パスワード確認用' %>

          <div class="flex items-center justify-center mt-1.5">
            <div class="rounded-md bg-yellow-600 h-7 w-4/5 hover:bg-yellow-500">
              <%= f.submit "アカウントを作成する", class: 'text-center h-7 w-full' %>
            </div>
          </div>
          <% end %>
        </div>
      </div>
      <div class="text-center mt-1.5">
        <!--Todo: href先を変える。cookieのコントローラを作成した後。-->
        <a class="hover:text-gray-400 text-xs" href="signin">ログインはこちら</a>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="flex">
    <%= render 'shared/left_column' %>
    <div class="w-6/12">
        <div class="mx-auto my-0 w-10/12">
            <div class="w-full">
                <div class="flex mt-1.5">
                    <div>
                        <!--Todo: 直下画像src変更する。画像保存先を決定していないので、保存先を決定出来次第変更する-->
                        <img class="h-28 w-28" src="data:image/png;base64, {{ user_image }}">
                    </div>
                    <div class="ml-1.5 w-96 break-all">
                        <div class="text-right">
                            <% if @user.id == current_user.id %>
                            <%= link_to 'プロフィールを編集する', edit_user_url %>
                            <% end %>
                        </div>
                        <div>
                            <span class="text-3xl font-bold">
                                <%= @user.name %>
                            </span>
                        </div>
                        <div>
                            <span>
                                @<%= @user.id %>
                            </span>
                        </div>
                        <div class="flex w-96 break-all">
                            <span>
                                <%= @user.self_introduction %>
                            </span>
                        </div>
                    </div>
                </div>
            </div>


            <%= render 'shared/passage_cards' %>
        </div>
    </div>
</div>