config/routes.rb
Rails.application.routes.draw do
  root 'passages#show_all'

  get 'login', to: 'cookies#new'
  get 'logout', to: 'cookies#show_log_out'
  resource :cookies, { only: %i[create destroy] }

  resources :users, path_names: { new: 'signup' } do
    resource :bookmarks, { only: %i[show] }

    resources :passages, { only: %i[create destroy show] } do
      get 'bookmarks', to: 'bookmarks#show_passage_bookmarks'
      post 'bookmarks/check', to: 'bookmarks#try_create_bookmark'
    end

    resources :comments, { only: %i[create destroy show] } do
      get 'likes', to: 'likes#show_comment_likes'
      post 'likes/check', to: 'likes#try_create_like'
    end
  end

  patch 'users/:id/update-name-self-introduction', to: 'users#update_name_self_introduction'
end

app/views/shared/_comment_form.html.erb
<% if @has_user_logged_in %>
<div class="block mr-0.5 ml-auto my-2.5 w-3/12">
  <%= form_with(model: @comment_form_model, url: {controller: 'comments', action: 'create', user_id: @current_user.id}, local: true) do |f| %>
  <%= f.text_area :content, placeholder: 'コメント', class: 'rounded-lg bg-gray-100 h-96 mt-2.5 py-1.5 pl-1.5 break-all w-full' %>

  <%= f.submit "投稿する", class: "hover:text-gray-400 mt-2.5" %>

  <% end %>
</div>
<% end %>

app/views/shared/_left_column.html.erb
<div class="w-3/12 ml-5rem my-2.5">
  <div class="m-auto mt-2.5 w-11/12">
    <%= link_to 'ホーム', root_url, class: "hover:text-gray-400" %>
  </div>
  <% if @has_user_logged_in %>
  <div class="m-auto mt-2.5 w-11/12">
    <%= link_to 'プロフィール', user_path(@current_user.id), class: "hover:text-gray-400" %>
  </div>
  <div class="m-auto mt-2.5 w-11/12">
    <%= link_to 'ログアウト', logout_path, class: "hover:text-gray-400" %>
  </div>
  <% else %>
  <div class="m-auto mt-2.5 w-11/12">
    <%= link_to '新規登録', new_user_path, class: "hover:text-gray-400" %>
  </div>
  <div class="m-auto mt-2.5 w-11/12">
    <%= link_to 'ログイン', login_path, class: "hover:text-gray-400" %>
  </div>
  <% end %>
</div>

app/views/shared/_passage_cards.html.erb
<% @passages.zip(@passages_bookmarks) do |passage, passage_bookmarks|%>
<div class="bg-blue-100 rounded-lg mt-2.5 mb-2.5">
  <div class="m-auto py-4">
    <div class="break-all ml-auto mr-auto w-96">
      <p><%= passage.content %></p>
    </div>
  </div>
  <div class="break-all m-auto w-96">
    <span><i class="fas fa-book-open mr-1.5"></i><%= passage.book_title %></span>
  </div>
  <div class="flex m-auto w-96">
    <span class="border-b border-black w-96 my-1.5"></span>
  </div>
  <div class="flex m-auto pb-1.5 w-96 break-all">
    <div class="w-5/12">
      <%= link_to passage.user_name, user_path(passage.user_id), class: "hover:text-gray-50" %>
    </div>
    <div class="flex w-3/12">
      <% if @has_user_logged_in %>
      <%= link_to user_passage_bookmarks_check_path(user_id: @current_user.id, passage_id: passage.id), method: :post do %>
      <i class="far fa-bookmark mr-1.5"></i>
      <% end %>
      <% else %>
      <i class="far fa-bookmark mr-1.5"></i>
      <% end %>
      <%= link_to passage_bookmarks, controller: "bookmarks", action: "show_passage_bookmarks", user_id: passage.user_id, passage_id: passage.id%>
    </div>
    <div class="w-2/12">
      <%= link_to 'コメント', user_passage_path(user_id: passage.user_id, id: passage.id), class: 'hover:text-gray-50' %>
    </div>
    <div class="text-right w-2/12">
      <% if passage.user_id == @current_user.id %>
      <%= link_to user_passage_path(user_id: @current_user.id, id: passage.id), method: :delete do %>
      <i class="fas fa-trash"></i>
      <% end %>
      <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_passage_form.html.erb
<% if @has_user_logged_in %>
<div class="block mr-0.5 ml-auto my-2.5 w-3/12">
  <%= form_with(model: @passage, url: {controller: 'passages', action: 'create', user_id: @current_user.id}, local: true, class: "w-full") do |f| %>
  <div class="m-auto w-11/12">
    <%= f.text_area :content, placeholder: "感動した文章", class: "rounded-lg bg-gray-100 h-96 mt-2.5 py-1.5 pl-1.5 break-all w-full" %>

    <%= f.text_area :book_title, placeholder: "本のタイトル", class: "rounded-lg bg-gray-100 mt-2.5 py-1.5 pl-1.5 w-full"%>

    <%= f.submit "投稿する", class: "hover:text-gray-400 mt-2.5" %>
  </div>
  <% end %>
</div>
<% end %>