config/routes.rb
Rails.application.routes.draw do
  root 'passages#show_all'

  get 'login', to: 'cookies#new'
  get 'logout', to: 'cookies#show_log_out'
  resource :cookies, { only: %i[create destroy] }

  resources :users, path_names: { new: 'signup' } do
    resource :bookmarks, { only: %i[show] }

    resources :passages, { only: %i[create destroy show] } do
      get 'bookmarks', to: 'bookmarks#show_passage_bookmarks'
      post 'bookmarks/check', to: 'bookmarks#try_create_bookmark'
    end

    resources :comments, { only: %i[create destroy show] } do
      get 'likes', to: 'likes#show_comment_likes'
      post 'likes/check', to: 'likes#try_create_like'
    end
  end

  patch 'users/:id/update-name-self-introduction', to: 'users#update_name_self_introduction'
end

app/controllers/cookies_controller.rb
class CookiesController < ApplicationController
  include ApplicationHelper

  def new; end

  def create
    user = User.find_by(id: params[:id])

    if user&.authenticate(params[:password])
      user.remember
      log_in(user)
      redirect_to root_url
    else
      redirect_to login_path
    end
  end

  def show_log_out; end

  def destroy
    user = User.find_by(id: current_user.id)
    log_out(user) if logged_in?
    redirect_to login_path
  end
end

app/helpers/cookies_helper.rb
module CookiesHelper
end

app/views/cookies/log_out.html.erb
<div class="bg-gray-300 flex items-center justify-center h-screen w-screen">
  <div class="bg-white rounded-lg h-72 w-72">
    <div class="flex items-center justify-center h-4/6">
      <h1 class="text-center">ログアウトしますか？</h1>
    </div>
    <div class="flex h-2/6 justify-around">
      <div class="rounded-lg w-5/12">
        <%= link_to "はい", cookies_path, method: :delete, class: "bg-gray-600 rounded-lg py-1.5 text-center w-full" %>
      </div>
      <div class="rounded-lg w-5/12">
        <%= link_to "いいえ", request.referer, class: "bg-gray-300 rounded-lg py-1.5 text-center" %>
      </div>
    </div>
  </div>
</div>

app/views/cookies/new.html.erb
<!-- Todo: 画像を設置出来次第有効にする
<div class="fixed" style="z-index: -1;">
  <img class="w-full" src="../static/img/login_background.png">
</div>
-->
<div class="flex items-center justify-center h-screen">
  <div class="flex items-center justify-center rounded-md h-96 w-72 bg-yellow-200">
    <div class="my-auto mx-1/5">
      <div class="mb-7 text-center">
        <h1 class="text-4xl font-bold">ブクエモ！</h1>
        <p class="text-base">心揺さぶる文章がここにある</p>
      </div>
      <div class="flex items-center justify-center">
        <div class="w-4/5">
          <%= form_with(url: {controller: 'cookies', action: 'create'}, local: true) do |f| %>
          <%= f.text_field :id, class: 'bg-white rounded-md h-7 mb-1.5 pl-2.5 w-full', placeholder: 'ユーザーid' %>

          <%= f.password_field :password, class: 'bg-white rounded-md h-7 mb-1.5 pl-2.5 w-full', placeholder: 'パスワード' %>

          <div class="flex items-center justify-center mt-1.5">
            <div class="rounded-md bg-yellow-600 h-7 w-4/5 hover:bg-yellow-500">
              <%= f.submit "ログイン", class: 'text-center h-7 w-full' %>
            </div>
          </div>
          <% end %>
        </div>
      </div>
      <div class="text-center mt-1.5">
        <%= link_to "アカウントを作成する", new_user_path, class: "hover:text-gray-400 text-xs"%>
      </div>
    </div>
  </div>
</div>

app/views/cookies/show_log_out.html.erb
<div class="bg-gray-300 flex items-center justify-center h-screen w-screen">
  <div class="bg-white rounded-lg h-72 w-72">
    <div class="flex items-center justify-center h-4/6">
      <h1 class="text-center">ログアウトしますか？</h1>
    </div>
    <div class="flex h-2/6 justify-around">
      <div class="rounded-lg w-5/12">
        <%= link_to "はい", cookies_path, method: :delete, class: "bg-gray-600 rounded-lg py-1.5 text-center w-full" %>
      </div>
      <div class="rounded-lg w-5/12">
        <%= link_to "いいえ", request.referer, class: "bg-gray-300 rounded-lg py-1.5 text-center" %>
      </div>
    </div>
  </div>
</div>