config/routes.rb
Rails.application.routes.draw do
  root 'passages#show_all'

  get 'login', to: 'cookies#new'
  get 'logout', to: 'cookies#show_log_out'
  resource :cookies, { only: %i[create destroy] }

  resources :users, path_names: { new: 'signup' } do
    resource :bookmarks, { only: %i[show] }

    resources :passages, { only: %i[create destroy show] } do
      get 'bookmarks', to: 'bookmarks#show_passage_bookmarks'
      post 'bookmarks/check', to: 'bookmarks#try_create_bookmark'
    end

    resources :comments, { only: %i[create destroy show] } do
      get 'likes', to: 'likes#show_comment_likes'
      post 'likes/check', to: 'likes#try_create_like'
    end
  end

  patch 'users/:id/update-name-self-introduction', to: 'users#update_name_self_introduction'
end

app/models/passage.rb
class Passage < ApplicationRecord
  belongs_to :user
  has_many :passages_comment_relations, dependent: :delete_all
  has_many :comments, through: :passages_comment_relations, dependent: :delete_all
  has_many :passage_bookmarks, dependent: :delete_all

  validates :content, presence: true, length: { maximum: 1023 }

  validates :book_title, length: { maximum: 255 }

  VALID_USER_ID_REGEX = /[a-zA-Z0-9_-]+/
  validates :user_id, presence: true, length: { maximum: 255 }, format: { with: VALID_USER_ID_REGEX }
end

app/controllers/passages_controller.rb
class PassagesController < ApplicationController
  include ApplicationHelper

  def create
    @passage = Passage.new(passage_params)

    @passage.book_title = '不明' if @passage.book_title == ''

    @passage.save

    redirect_to root_url
  end

  def show
    passage_id = params[:id].to_i

    @passage = User.joins(:passages).where(passages: { id: passage_id }).select('users.name as user_name, passages.*').first
    @passage_bookmarks = Passage.eager_load(:passage_bookmarks).where(passages: { id: passage_id }).group('passages.id').count('passage_bookmarks.id')[passage_id]

    @comment_form_model = Comment.new
    @comments = User.joins(comments: :passages_comment_relation).where(passages_comment_relations: { passage_id: passage_id })
                    .select('users.id as user_id, users.name as user_name, comments.content as content, comments.id as id')
                    .order('comments.created_at desc').order('comments.user_id asc')

    @comments_likes = Passage.joins(:comments).eager_load(comments: :comment_likes).where(passages: { id: passage_id })
                             .group('comments.id').count('comment_likes.id')

    @current_user = current_user
  end

  def show_all
    @passage = Passage.new
    @passages = User.joins(:passages).select('users.name as user_name, passages.*').order('passages.created_at desc').order('passages.user_id asc')
    @passages_bookmarks = Passage.eager_load(:passage_bookmarks)
                                 .select('passages.id as passage_id')
                                 .order('passages.created_at desc').order('passages.user_id asc')
                                 .group('passages.id')
                                 .count('passage_bookmarks.id').map { |_key, value| value }

    @current_user = current_user

    @has_user_logged_in = logged_in?
  end

  def destroy
    @passage = Passage.find_by(id: params[:id])
    @passage.destroy!
    redirect_to root_url
  end

  private

  def passage_params
    params.require(:passage).permit(:content, :book_title).merge(user_id: current_user.id)
  end
end

app/helpers/passages_helper.rb
module PassagesHelper
end

app/views/passages/show.html.erb
<div class="flex">
  <%= render 'shared/left_column' %>
  <div class="w-6/12">
    <div class="mx-auto my-0 w-10/12">
      <div class="bg-blue-100 rounded-lg mt-2.5 mb-2.5">
        <div class="m-auto py-4">
          <div class="break-all ml-auto mr-auto w-96">
            <p><%= @passage.content %></p>
          </div>
        </div>
        <div class="break-all m-auto w-96">
          <span><i class="fas fa-book-open mr-1.5"></i><%= @passage.book_title %></span>
        </div>
        <div class="flex m-auto w-96">
          <span class="border-b border-black w-96 my-1.5"></span>
        </div>
        <div class="flex m-auto pb-1.5 w-96 break-all">
          <div class="w-5/12">
            <%= link_to @passage.user_name, user_path(@passage.user_id) %>
          </div>
          <div class="flex w-3/12">
            <% if @has_user_logged_in %>
            <%= link_to user_passage_bookmarks_check_path(user_id: @current_user.id, passage_id: @passage.id), method: :post do %>
            <i class="far fa-bookmark mr-1.5"></i>
            <% end %>
            <% else %>
            <i class="far fa-bookmark mr-1.5"></i>
            <% end %>
            <%= link_to @passage_bookmarks, controller: "bookmarks", action: "show_passage_bookmarks", user_id: @passage.user_id, passage_id: @passage.id%>
          </div>
          <% if @passage.user_id == @current_user.id %>
          <div class="text-right ml-auto w-2/12">
            <%= link_to user_passage_path(user_id: @current_user.id, id: @passage.id), method: :delete do %>
            <i class="fas fa-trash"></i>
            <% end %>
          </div>
          <% end %>
        </div>
      </div>


      <div class="my-1.5">
        <% @comments.each do |comment| %>
        <div class="bg-blue-100 rounded-lg mt-2.5 mb-2.5">
          <div class="m-auto py-4">
            <div class="break-all ml-auto mr-auto w-96">
              <p><%= comment.content %></p>
            </div>
          </div>
          <div class="flex m-auto w-96">
            <span class="border-b border-black w-96 my-1.5"></span>
          </div>
          <div class="flex m-auto pb-1.5 w-96 break-all">
            <div class="w-5/12">
              <%= link_to comment.user_name, user_path(comment.user_id), class: "hover:text-gray-400" %>
            </div>
            <div class="flex w-3/12">
              <% if @has_user_logged_in %>
              <%= link_to user_comment_likes_check_path(user_id: @current_user.id, comment_id: comment.id), method: :post do %>
              <i class="far fa-heart m-r-5"></i>
              <% end %>
              <% else %>
              <i class="far fa-heart m-r-5"></i>
              <% end %>
              <%= link_to @comments_likes[comment.id.to_i], controller: "likes", action: "show_comment_likes", user_id: comment.user_id, comment_id: comment.id %>
            </div>
            <div class="w-2/12">
              <%= link_to 'コメント', user_comment_path(user_id: comment.user_id, id: comment.id), class: "hover:text-gray-400"%>
            </div>
            <% if comment.user_id == @current_user.id %>
            <div class="text-right w-2/12">
              <%= link_to user_comment_path(user_id: comment.user_id, id: comment.id), method: :delete do %>
              <i class="fas fa-trash"></i>
              <% end %>
            </div>
            <% end %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
  <%= render 'shared/comment_form' %>
</div>

app/views/passages/show_all.html.erb
<div class="flex">
  <%= render 'shared/left_column' %>
  <div class="w-6/12">
    <div class="mx-auto my-0 w-10/12">
      <%= render 'shared/passage_cards' %>
    </div>
  </div>
  <%= render 'shared/passage_form' %>
</div>